### ISSUE TITLE
쳅터단위로 파일 저장할것

### ISSUE THREAD

**Issue by jongchan988** [UDIL1852/Practice#2]
지금  파일들이 Practice/src/main/java/ 하위에 있는데
챕터별로 폴더만들어서
Practice/src/main/java/chapter2 
이런식으로 구분해야 좋을듯

**Comment by UDIL1852** [comment]
한번 옮겨봤는데 시간 될 때 이게 맞는지 검토해줘

**Comment by jongchan988** [comment]
어제 정신이 없어서 제대로 못봤는데. 내가 말하는 챕터의 기준은 책의 챕터랑 같음.
